# Site settings
title: Apache Fluo
baseurl: "" # the subpath of site
url: "https://fluo.apache.org/" # the base hostname & protocol for your site
timezone: Etc/UTC

permalink: pretty

defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "default"
  -
    scope:
      path: "_posts/blog"
      type: "posts"
    values:
      layout: "post"
      category: "blog"
  -
    scope:
      path: "_posts/release"
      type: "posts"
    values:
      layout: "release"
      category: "release"
      permalink: "/:categories/:title/"
  - 
    scope:
      path: "tour"
      type: "pages"
    values:
      layout: "tour"
      permalink: "/tour/:basename/"

# Number of posts displayed on the home page.
num_home_posts: 5

# Color scheme based on http://flatuicolors.com/.
color: default

# Fluo specific settings
latest_fluo_release: "1.0.0-incubating"
latest_fluo_release_date: "October 4, 2016"
latest_recipes_release: "1.0.0-beta-2"
latest_recipes_release_date: "March 29, 2016"

# Sets links to external API
api_base: "https://javadoc.io/doc/org.apache.fluo"
api_static: "https://static.javadoc.io/org.apache.fluo"
fluo_api_base: "https://javadoc.io/doc/org.apache.fluo/fluo-api"
fluo_api_static: "https://static.javadoc.io/org.apache.fluo/fluo-api"
old_api_base: "https://javadoc.io/doc/io.fluo"
old_api_static: "https://static.javadoc.io/io.fluo"

whitelist: [jekyll-redirect-from]
gems: [jekyll-redirect-from]

kramdown:
  input: GFM
  syntax_highlighter: rouge
  hard_wrap: false
